- hosts: all
  become: yes
  roles:
    - certificates
    - docker
    - kubernetes
    - common

- hosts: buildservers
  become: yes
  roles:
    - jenkins

- hosts: utviklerimages
  become: yes
  vars_prompt:
    - name: "ident"
      prompt: "Enter your NAV ident"
      private: no
    - name: "ident_domain"
      prompt: "Enter domain"
      default: "adeo.no"
      private: no
    - name: "ident_password"
      prompt: "Enter your NAV password"
      private: yes
  roles:
    - linuximage
    - kubeconfigs
