- name: Add kubernetes repository
  yum_repository:
    name: Kubernetes
    description: Kubernetes
    file: kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
    enabled: true
    gpgkey:
      - https://packages.cloud.google.com/yum/doc/yum-key.gpg
      - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    gpgcheck: false
    repo_gpgcheck: false
    state: present

- name: "Install kubectl-{{ kubectl_version }}"
  yum:
    name: "kubectl-{{ kubectl_version }}"
    state: present
    update_cache: yes
