#
# Install Jenkins
#
- name: Add Jenkins repository
  yum_repository:
    name: Jenkins
    description: Jenkins
    baseurl: https://pkg.jenkins.io/redhat-stable
    enabled: true
    gpgkey: https://jenkins-ci.org/redhat/jenkins-ci.org.key
    gpgcheck: true
    state: present

- name: "install jenkins {{ jenkins_version }}"
  yum:
    name: "jenkins-{{ jenkins_version }}"
    state: latest

- name: Add jenkins to docker group
  user:
    name: jenkins
    group: docker
    append: yes

#
# git config for Jenkins
#
- name: Setup default git configuration
  template:
    src: templates/gitconfig.j2
    dest: /var/lib/jenkins/.gitconfig
    owner: jenkins
    group: jenkins
    mode: 0644

#
# start jenkins service
#
- name: Enable and start jenkins service
  systemd:
    name: jenkins
    state: started
    enabled: yes
