#
# Install/Update git
#
- name: install git
  yum:
    name: git
    state: latest

#
# Install java
#
- name: install java
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - java-1.7.0-openjdk-devel
    - java-1.8.0-openjdk-devel

- name: set java 1.8 as default
  alternatives:
    name: java
    link: /usr/bin/java
    path: /usr/lib/jvm/java-1.8.0-openjdk/bin/java

- name: set javac 1.8 as default
  alternatives:
    name: javac
    link: /usr/bin/javac
    path: /usr/lib/jvm/java-1.8.0-openjdk/bin/javac

#
# Install maven
#
- name: "Download maven-{{ maven_version }}"
  get_url:
    url: "http://apache.uib.no/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz"
    dest: "/opt/apache-maven-{{ maven_version }}-bin.tar.gz"
    timeout: 60

- name: "Install maven-{{ maven_version }}"
  unarchive:
    src: "/opt/apache-maven-{{ maven_version }}-bin.tar.gz"
    dest: /opt
    remote_src: yes

- name: "set maven {{ maven_version }} as default"
  alternatives:
    name: mvn
    link: /usr/bin/mvn
    path: "/opt/apache-maven-{{ maven_version }}/bin/mvn"

- name: Download maven settings.xml
  get_url:
    url: "{{ maven_internal_url }}/software/maven/settings.xml"
    dest: "/opt/apache-maven-{{ maven_version }}/conf/settings.xml"
    force: yes
  when: maven_internal_url is defined

#
# Install node
#
- name: "Download and Install node-{{ node_version }}"
  unarchive:
    src: "https://nodejs.org/dist/v{{ node_version }}/node-v{{ node_version }}-linux-x64.tar.xz"
    dest: /opt
    remote_src: yes

- name: "set node {{ node_version }} as default"
  alternatives:
    name: node
    link: /usr/bin/node
    path: "/opt/node-v{{ node_version }}-linux-x64/bin/node"

- name: "set npm {{ node_version }} as default"
  alternatives:
    name: npm
    link: /usr/bin/npm
    path: "/opt/node-v{{ node_version }}-linux-x64/bin/npm"

- name: Setup npmrc
  copy: src=files/npmrc dest=/etc/npmrc
  when: proxy_env.http_proxy|default("") != ""

- name: Specifying subnet for vmware-viewagent
  lineinfile:
    dest: /etc/vmware/viewagent-custom.conf
    regexp: '#?Subnet='
    line: "Subnet={{ vmware_subnet }}"
